version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toggle_system
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      
volumes:
  db-data:
    name: "postgres-data"
    driver: local